# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_firstname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_title',
        ),
        migrations.AddField(
            model_name='person',
            name='GSA_labor',
            field=models.CharField(default='N/A', max_length=100, verbose_name='GSA Labor Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='GSA_rate',
            field=models.CharField(default='N/A', max_length=100, verbose_name='GSA Rate'),
        ),
        migrations.AddField(
            model_name='person',
            name='GSA_vehicle',
            field=models.CharField(default='N/A', max_length=100, verbose_name='GSA Vehicle'),
        ),
        migrations.AddField(
            model_name='person',
            name='HUBzone',
            field=models.BooleanField(default=True, verbose_name='HUBzone'),
        ),
        migrations.AddField(
            model_name='person',
            name='PMI_career_title',
            field=models.CharField(default='N/A', max_length=100, verbose_name='PMI Career Title    '),
        ),
        migrations.AddField(
            model_name='person',
            name='PMI_email',
            field=models.CharField(default='N/A', max_length=100, verbose_name='PMI Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='_401k_eligible',
            field=models.BooleanField(default=True, verbose_name='401K Eligible'),
        ),
        migrations.AddField(
            model_name='person',
            name='billable',
            field=models.CharField(choices=[('B', 'Billable'), ('N', 'Non-Billable')], default='N/A', max_length=50, verbose_name='Billable/Non-Billable'),
        ),
        migrations.AddField(
            model_name='person',
            name='business_cards',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Business Cards (if needed provide info to include)'),
        ),
        migrations.AddField(
            model_name='person',
            name='campin',
            field=models.BooleanField(default=True, verbose_name='CAMPIN Sent to Candidate'),
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_packet',
            field=models.BooleanField(default=True, verbose_name='Clearance Packet Complete'),
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_packet_sent',
            field=models.BooleanField(default=True, verbose_name='Completed Clearance Packet Sent to JA'),
        ),
        migrations.AddField(
            model_name='person',
            name='clearance_packet_submitted',
            field=models.BooleanField(default=True, verbose_name='Clearance Packet Submitted to Census'),
        ),
        migrations.AddField(
            model_name='person',
            name='cleared_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Cleared Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='client_bill',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Client Bill Rate'),
        ),
        migrations.AddField(
            model_name='person',
            name='clock_sequence',
            field=models.IntegerField(default=0, max_length=50, verbose_name='Clock Sequence'),
        ),
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.CharField(default='N/A', max_length=400, verbose_name='Comments (Task Codes, Invoicing POC, COI)'),
        ),
        migrations.AddField(
            model_name='person',
            name='commission_due',
            field=models.DateField(default=datetime.date.today, verbose_name='Commission Due Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='commission_logged',
            field=models.BooleanField(default=True, verbose_name='Commission Logged?'),
        ),
        migrations.AddField(
            model_name='person',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Completed'),
        ),
        migrations.AddField(
            model_name='person',
            name='computer',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Computer'),
        ),
        migrations.AddField(
            model_name='person',
            name='contract_labor',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Contract Labor Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_hire',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Hire'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Department/Project Assigned'),
        ),
        migrations.AddField(
            model_name='person',
            name='discount',
            field=models.IntegerField(default=0, max_length=50, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='person',
            name='efaact',
            field=models.CharField(default='N/A', max_length=100, verbose_name='eFAACT'),
        ),
        migrations.AddField(
            model_name='person',
            name='employment_status',
            field=models.CharField(choices=[('C', 'Current'), ('F', 'Former'), ('L', 'Leave')], default='N/A', max_length=50, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='person',
            name='gb_security_r',
            field=models.CharField(default='N/A', max_length=400, verbose_name='GB Security Access Request'),
        ),
        migrations.AddField(
            model_name='person',
            name='google_groups',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Google Groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_address',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='hourly_pay',
            field=models.IntegerField(default=0, max_length=50, verbose_name='Hourly Pay Rate'),
        ),
        migrations.AddField(
            model_name='person',
            name='offer_contract',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Offer Contract/NDA FE'),
        ),
        migrations.AddField(
            model_name='person',
            name='offer_sent',
            field=models.BooleanField(default=True, verbose_name='Offer/Contract Sent'),
        ),
        migrations.AddField(
            model_name='person',
            name='orientation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Orientation Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='paycom_login',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Paycom Login'),
        ),
        migrations.AddField(
            model_name='person',
            name='payroll_company',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Payroll Company'),
        ),
        migrations.AddField(
            model_name='person',
            name='probationary_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Probationary End'),
        ),
        migrations.AddField(
            model_name='person',
            name='project_title',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Project/Functional Title'),
        ),
        migrations.AddField(
            model_name='person',
            name='recruitment_source',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Recruitment Source'),
        ),
        migrations.AddField(
            model_name='person',
            name='rehire',
            field=models.BooleanField(default=True, verbose_name='Rehire (T/F)'),
        ),
        migrations.AddField(
            model_name='person',
            name='resource_email',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Resource Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='resource_first_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Resource First Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='resource_last_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Resource Last Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='resource_telephone',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Resource Personal Telephone'),
        ),
        migrations.AddField(
            model_name='person',
            name='resource_type',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Resource Type'),
        ),
        migrations.AddField(
            model_name='person',
            name='responsible_recruiter',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Responsible Recruiter'),
        ),
        migrations.AddField(
            model_name='person',
            name='software_r',
            field=models.CharField(default='N/A', max_length=400, verbose_name='Software Requests'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='person',
            name='supervisor_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Supervisor Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='termination_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Termination Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='toolkit',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Toolkit'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_location',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Work Location'),
        ),
    ]
