# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogdb', '0002_auto_20170208_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='resource_telephone',
            field=models.CharField(default='000-000-0000', max_length=100, verbose_name='Resource Personal Telephone'),
        ),
    ]
